server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
  port: '8080'

spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    hikari:
      username: sa
      #jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      url=jdbc:h2:tcp://localhost/~/test;MODE=MySQL:
    driverClassName: org.h2.Driver
    password: '1234'
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw | base64 YWprbGdoc2Rma2xnanNkaGZnbGprc2RmZ2hsc2
  access-token-validity-in-seconds: 600 # 10 min